# Connexion du client à l’application avec son email comme identifiant et vérification du mot de passe
SELECT IDCompte FROM UTILISATEUR WHERE EMAIL = '' AND MotDePasse = '';

#Parcours des catégories et sous-catégories,
SELECT * FROM CATEGORIE

#parcours des catégories recommandées
#En pririte

# par categorie
SELECT NOMPARENT, COUNT(NOMPARENT) AS NBR FROM (SELECT NOMC, H.IDPROD FROM (SELECT P.IDPROD, P.NOMC FROM ((SELECT IDPROD,IDCOMPTE FROM OFFRE WHERE IDCOMPTE = 'KB9999999')
MINUS
(SELECT IDPROD,IDCOMPTE FROM OFFRE_GAGNANTE WHERE IDCOMPTE = 'KB9999999')) M
JOIN PRODUIT P ON P.IDPROD = M.IDPROD WHERE M.IDCOMPTE = 'KB9999999') H
JOIN OFFRE O ON O.IDPROD = H.IDPROD WHERE O.IDCOMPTE = 'KB9999999') B
JOIN A_PARENT A ON A.NOMC = B.NOMC
GROUP BY NOMPARENT
ORDER BY NBR DESC

# par souscategorie
SELECT COUNT(NOMC) AS NBR, NOMC FROM (SELECT P.IDPROD, P.NOMC FROM ((SELECT IDPROD,IDCOMPTE FROM OFFRE WHERE IDCOMPTE = 'KB9999999')
MINUS
(SELECT IDPROD,IDCOMPTE FROM OFFRE_GAGNANTE WHERE IDCOMPTE = 'KB9999999')) M
JOIN PRODUIT P ON P.IDPROD = M.IDPROD WHERE M.IDCOMPTE = 'KB9999999') H
JOIN OFFRE O ON O.IDPROD = H.IDPROD WHERE O.IDCOMPTE = 'KB9999999'
GROUP BY NOMC
ORDER BY NBR DESC

## recommendation2

# Par CATEGORIE
SELECT SUM(NBR)/COUNT(*) AS FINAL_NBR, M.NOMPARENT FROM (SELECT COUNT(*) AS NBR,NomParent, IDPROD  FROM (SELECT O.IDPROD, P.NOMC  FROM OFFRE O
JOIN PRODUIT P
ON P.IDPROD = O.IDPROD) H
JOIN A_PARENT A
ON H.NOMC = A.NOMC
GROUP BY NOMPARENT, IDPROD) M
GROUP BY M.NOMPARENT
ORDER BY FINAL_NBR DESC

# par souscategorie
SELECT SUM(NBR)/COUNT(*) AS FINAL_NBR,NOMC  FROM (SELECT COUNT(*) AS NBR, NOMC,IDPROD FROM (SELECT O.IDPROD, P.NOMC  FROM OFFRE O
JOIN PRODUIT P
ON P.IDPROD = O.IDPROD) H
GROUP BY NOMC, IDPROD) M
GROUP BY M.NOMC
ORDER BY FINAL_NBR DESC


# Consultation des produits
SELECT H.IDPROD, H.INTITULE, H.PRIXCOURANT, H.URL, H.NOMC FROM (SELECT COUNT(*) AS NBROFFRE,P.IDPROD, P.INTITULE, P.PRIXCOURANT, P.URL, P.NOMC  FROM PRODUIT P
LEFT JOIN OFFRE O
ON P.IDPROD = O.IDPROD
WHERE NOMC IN ((SELECT * FROM CATEGORIE WHERE NomC = 'Pantalon de sport') UNION (SELECT A.NomC FROM CATEGORIE C JOIN A_PARENT A ON C.NomC = A.NomParent WHERE C.NomC = 'Pantalon de sport')) AND P.IDPROD NOT IN (SELECT IDPROD FROM OFFRE_GAGNANTE)
GROUP BY P.IDPROD, P.INTITULE, P.PRIXCOURANT, P.URL, P.NOMC
ORDER BY NBROFFRE DESC) H

# Contrainte PrixPropose > PrixCourant
Begin;
INSERT INTO OFFRE VALUES ('PR13', to_date('2021-03-11 22:53:00', 'YYYY-MM-DD HH24:MI:SS'), 31, 'CR7777777');
DELETE FROM OFFRE WHERE IDCompte = 'CR7777777' and PrixPropose <= PrixCourant and Heure = to_date('2021-03-11 22:53:00', 'YYYY-MM-DD HH24:MI:SS');
UPDATE PRODUIT SET PrixCourant = PrixPropose WHERE PrixPropose > PrixCourant AND IdProd = 'PR13' AND IDProd NOT IN (Select IDProd FROM OFFRE_GAGNANTE);
Commit;
